notifications:
  email:
    - mig-travis@cern.ch
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
services:
  - rabbitmq
# command to install dependencies
install:
  - pip install auth.credential
  - pip install argparse || echo "not needed from 3.2 on, ok"
  - pip install dirq
  - pip install messaging
  - pip install pika
  - pip install anyjson
  - pip install amqplib
  - pip install kombu
  - pip install pep8
  - pip install pylint
  - curl -O -R -S -f -s https://raw.github.com/cern-mig/dev-tools/master/python/pylint.sh
  - curl -O -R -S -f -s https://raw.github.com/cern-mig/dev-tools/master/python/.pylintrc
# command to run tests
script:
  - pep8 bin/amqpclt amqpclt test
  - sh pylint.sh bin/amqpclt amqpclt test || echo "*ignored*"
  - python setup.py install --no-data-files
# changing python path to include current directory in order to run tests
  - export PYTHONPATH=$PYTHONPATH:.
  - python setup.py test
